name: "Build Android ROM"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: "Build Android ROM"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt-get install git-core
          git clone https://github.com/akhilnarang/scripts
          cd scripts
          bash setup/ubuntu1604linuxmint18.sh
          mkdir -p ~/bin
          mkdir -p ~/android/lineage
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          cd ~/android/lineage
      - name: Clone and sync ROM repository
        run: |
          git clone https://github.com/LineageOS.git
          cd LineageOS
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
          repo sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --force-broken
      - name: Build ROM
        run: |
          cd LineageOS
          source build/envsetup.sh
          lunch lineage_twolip-user
          make -j$(nproc) bacon
      - name: Upload ROM artifact
        uses: actions/upload-artifact@v2
        with:
          name: ROM
          path: LineageOS/out/target/product/target_device/*.zip
